name: msvc

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --target plugify

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} --parallel
