name: msys2-mingw

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'include/**'
      - 'src/**'
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  CMAKE_GENERATOR: Ninja

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW64
        install: mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc mingw-w64-x86_64-curl

    - name: Configure CMake
      run: >
        cmake -G Ninja -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --target plugify --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}