name: msys2-mingw

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CMAKE_GENERATOR: Ninja

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: msys2 {0}

      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]
        c_compiler: [gcc]
        c_compiler: [g++]
        cpp_version: [c++20, c++23]

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW64
        install: mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc mingw-w64-x86_64-curl

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install curl
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install -y libcurl4-openssl-dev

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --target plugify --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}